"""Regression test for a real-world extraction bug: pdfplumber's own column-boundary detection
can drift row to row (not just page to page) within a single ruled table - splitting one column
into two, or merging two into one - on statements from at least one real bank (Utkarsh Bank,
generated by an older JasperReports/iText pipeline). Trusting raw cell *index* against the
header's column count silently misreads the Balance column for every affected row, which breaks
reconciliation and can starve narration-based classification of the balance evidence it needs.

No real statement or personal data is used here - this reproduces the structural pattern
(a phantom extra column appearing partway through the statement) with a synthetic table.
"""
from __future__ import annotations

import sys

sys.path.insert(0, "/home/claude/ledgerlens/backend")

from app.extract_pdf import _bucket_row
from app.layout import _FOOTER


def test_bucket_row_absorbs_a_split_column():
    # Header: Date | Narration | Debit | Credit | Balance
    col_ranges = [(20.0, 60.0), (65.0, 300.0), (305.0, 360.0), (365.0, 420.0), (425.0, 480.0)]

    # A later row where the table finder split the Balance column into two adjacent cells
    # (e.g. "1,25,980.91" and "CR" detected as separate columns) - six cells for a five-column
    # header, with the tail two both geometrically under "Balance".
    texts = ["06-Feb-2026", "CASH WITHDRAWAL BY SELF", "1,00,000.00", "", "1,25,980.91", "CR"]
    geoms = [
        (20.0, 0, 60.0, 0), (65.0, 0, 300.0, 0), (305.0, 0, 360.0, 0),
        None, (425.0, 0, 460.0, 0), (461.0, 0, 480.0, 0),
    ]
    aligned = _bucket_row(texts, geoms, col_ranges)
    assert aligned == [
        "06-Feb-2026", "CASH WITHDRAWAL BY SELF", "1,00,000.00", "", "1,25,980.91 CR",
    ], aligned


def test_bucket_row_absorbs_a_merged_column():
    col_ranges = [(20.0, 60.0), (65.0, 300.0), (305.0, 360.0), (365.0, 420.0), (425.0, 480.0)]
    # A row where Debit and Credit merged into one detected cell (four cells for five columns) -
    # the money value should still land under Credit (nearest to its own range), not spill into
    # the merged cell's other half.
    texts = ["25-Feb-2026", "NEFT//XUTR/CMS.../ KOTAK LIFE INSURANCE", "9,740.67", "1,35,721.58 CR"]
    geoms = [(20.0, 0, 60.0, 0), (65.0, 0, 300.0, 0), (365.0, 0, 420.0, 0), (425.0, 0, 480.0, 0)]
    aligned = _bucket_row(texts, geoms, col_ranges)
    assert aligned[3] == "9,740.67"
    assert aligned[4] == "1,35,721.58 CR"


def test_footer_matches_registered_and_corporate_office():
    # "registered office" as one contiguous phrase used to be the only pattern matched; real
    # statements phrase it with words in between ("Registered & Corporate Office").
    assert _FOOTER.search(
        "Registered & Corporate Office : Utkarsh Tower, NH-31 (Airport Road), Varanasi"
    )
    assert _FOOTER.search("Regd. Office: Some Address")
    assert _FOOTER.search("Statement Summary")
    # must not misfire on real transaction narrations
    assert not _FOOTER.search("Cash withdrawal by Self/PUSA ROAD/947941")
    assert not _FOOTER.search("NEFT//XUTR/CMS1152502689316/ KOTAK LIFE INSURANCE")


if __name__ == "__main__":
    test_bucket_row_absorbs_a_split_column()
    test_bucket_row_absorbs_a_merged_column()
    test_footer_matches_registered_and_corporate_office()
    print("all tests passed")
